<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>disable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.11" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.2.3" />
    <PackageReference Include="Swashbuckle.AspNetCore.Filters" Version="10.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\common\TeamFlow.Common.Dto\TeamFlow.Common.Dto.csproj" />
    <ProjectReference Include="..\..\common\TeamFlow.Common\TeamFlow.Common.csproj" />
    <ProjectReference Include="..\TeamFlow.Projects.Handlers\TeamFlow.Projects.Handlers.csproj" />
  </ItemGroup>

</Project>
