<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\common\TeamFlow.Common.Dto\TeamFlow.Common.Dto.csproj" />
    <ProjectReference Include="..\..\common\TeamFlow.Common\TeamFlow.Common.csproj" />
    <ProjectReference Include="..\..\db\TeamFlow.DB\TeamFlow.DB.csproj" />
  </ItemGroup>

</Project>
